###
POST http://localhost:4004/emission/insertNewBuilding HTTP/1.1
Content-Type: application/json

{
    "emissions" : [
        {"emission_name" : "hotwater", "emission_level" : 1}
    ]
}

###
GET http://localhost:4004/emission/Buildings(123e4567-e89b-12d3-a456-426655440000)/getBuildingEmission() HTTP/1.1
